### ISSUE TITLE
Adding a PHP 5.6 compatible branch

### ISSUE THREAD

**Issue by JasonTheAdams** [inpsyde/WPSR7#2]
I'm looking to use this library in a WordPress plugin I'm developing, and was very excited to find it as another library expects the HTTP Response/Request to use PSR-7. Thanks for making and sharing this!

Unfortunately, I found that the library requires PHP 7 to work. I'm hoping for my plugin to work on PHP 5.5, but can settle for PHP 5.6, if necessary. As much as I'd like everyone to use PHP 7.x, a lot of WP sites still run on 5.x.

I was looking through the code and found that the PHP 7 features used really aren't mission critical:
- Non 5.x parameter types (i.e. `string $method = ''`)
- Method return types
- Null coalesce operators

While these are handy, they're not entirely necessary. I was wondering what the motive was to make this PHP 7.x exclusive, and if you'd consider adding a PHP 5.6 branch. That will at least allow folks to grab what they need via composer. I could just fork this for my own purposes, but thought it might help this library be open to more folks.

Thanks!

**Comment by gmazzap** [comment]
Hi @JasonTheAdams and thanks for your interest in the package.

The thing is that the mission-critical thing regarding support PHP 5 is... the support of PHP 5 itself.

In other words, supporting PHP 5 add concerns that we are not willing to address. As you probably know, supporting open source is never easy and requires effort from the company that basically get nothing in exchange (nothing that helps paying the bills, at least).

We write open source because we think we developers in the company can grow doing that, and because we want to help the community going forward, and for both things the support of a dead version of the language is of no help.

Moreover, we _use_ the open source we write. Our client and our workflow are based on PHP 7 as minimum version... adding support for PHP 5 is of not benefit for us, and we are not willing to add concerns to our open source (which might impact our clients) for something that bring us no benefit. As said above, we don't pay the bills with open source, but at least we don't want to make our bills more expensive because open source.

Finally, besides the _current_ state of the package, we fill that support for PHP 5 is something that holds back the _future_ development of the package...

So, I'm sorry, but I don't see support for PHP 5 in the scope of this (or any other) Inpsyde package.
